### ISSUE TITLE
Viewport controls

### ISSUE THREAD

**Issue by x421** [limikaeugr/MicromanagmentHell#21]
Today I thougt about the controls of the game. I think the first way of controlling should be mouse only, by controlling the viewport with edge scroll and clicking on nodes (a node is a building/resource/...). Later on we should implement controls via keybord:

Action | Key
------ | ---
Scroll Left | A
Scroll Right | D
Scroll Up | W
Scroll Down | S
Jump Node Left | J
Jump Node Right | I
Jump Node Up | U
Jump Node Down | K
Activate Node Menu | Space
Next Menu Item | Down
Prev Menu Item | UP
Open Submenu | Right
Close (Sub)Menu | Left
… | …

Last but not least we should implement a "cursor movement" where the map moves and not the cursor. This would allow players to use a gamepad (with specific menu bindings of course) without pain. 

I'd say it is important to give the players the ability to play how they want it, if it is with mouse or keyboard only, a mix or a gamepad.

**Comment by fortytwo-studio** [comment]
I played a bit around with viewport controls and it seems with the LWJGL a controller or mouse driven controls are pretty easy to implement.
I already tested keyboard functionalities to control the viewport and mouse controls (you know like moving the mouse cursor to the edge of the screen, like in every other strategy game on PC).
