### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by fortytwo-studio** [limikaeugr/MicromanagmentHell#32]
We could implement mod support to make it easier for the users.

**Comment by x421** [comment]
That is what part of what @thebrible is doing with #31 
The users can use the zips the same way we do, adding resources, recipes, buildings and events to the game. Only thing missing is the idea behind spawning events, we would have to implement a listener for that but it is in the zip spec. As for graphics we have to wait till the next sprint, but I guess it could be implemented fairly quick to map textures to those low polygon models?

**Comment by x421** [comment]
Oh, and we already talked about the music folder, so a user can use its own music in the game. Not sure if we should allow to swap game sounds, but if @Keani is the man for that matter.
